# Generated by Django 5.2.8 on 2025-12-04 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_otp_delete_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='collector',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.district'),
        ),
        migrations.AddField(
            model_name='collector',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.province'),
        ),
    ]
