# Generated by Django 4.2.27 on 2026-01-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_add_geolocation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastecategory',
            name='image',
            field=models.ImageField(blank=True, help_text='Image for waste category', null=True, upload_to='waste_categories/'),
        ),
    ]
